# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='player_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teams',
            name='player_tag',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
