# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-27 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0002_auto_20180531_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arenas',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('arena', models.IntegerField(default=0)),
                ('tv_arena', models.CharField(max_length=30)),
                ('is_in_use', models.BooleanField()),
                ('training_camp', models.BooleanField()),
                ('trophy_limit', models.IntegerField(default=0)),
                ('demote_trophy_limit', models.IntegerField(default=0)),
                ('chest_reward_multiplier', models.IntegerField(default=0)),
                ('shop_chest_reward_multiplier', models.IntegerField(default=0)),
                ('request_size', models.IntegerField(default=0)),
                ('max_donation_count_common', models.IntegerField(default=0)),
                ('max_donation_count_rare', models.IntegerField(default=0)),
                ('max_donation_count_epic', models.IntegerField(default=0)),
                ('matchmaking_min_trophy_delta', models.IntegerField(default=0)),
                ('matchmaking_max_trophy_delta', models.IntegerField(default=0)),
                ('matchmaking_max_seconds', models.IntegerField(default=0)),
                ('daily_donation_capacity_limit', models.IntegerField(default=0)),
                ('battle_reward_gold', models.IntegerField(default=0)),
                ('season_reward_chest', models.CharField(max_length=30)),
                ('quest_cycle', models.CharField(max_length=30)),
                ('force_quest_chest_cycle', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('arena_id', models.IntegerField(default=0)),
                ('league_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('image', models.URLField(default='https://royaleapi.com/static/img/badge/no_clan.png')),
            ],
        ),
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utcTime', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(max_length=30)),
                ('challengeType', models.CharField(max_length=30)),
                ('mode_name', models.CharField(max_length=30)),
                ('mode_deck', models.CharField(max_length=30)),
                ('mode_cardLevels', models.IntegerField(default=0)),
                ('mode_overtimeSeconds', models.IntegerField(default=0)),
                ('mode_players', models.CharField(max_length=30)),
                ('mode_sameDeck', models.NullBooleanField()),
                ('winCountBefore', models.IntegerField(default=0)),
                ('deckType', models.CharField(max_length=30)),
                ('teamSize', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=0)),
                ('teamCrowns', models.IntegerField(default=0)),
                ('opponentCrowns', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('elixir', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=30)),
                ('rarity', models.CharField(max_length=30)),
                ('arena', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Clans',
            fields=[
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('memberCount', models.IntegerField(default=0)),
                ('requiredScore', models.IntegerField(default=0)),
                ('donations', models.IntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clanwar.Badges')),
            ],
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('isCountry', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crownsEarned', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Battles')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Decks')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('trophies', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=30)),
                ('donations', models.IntegerField(default=0)),
                ('donationsReceived', models.IntegerField(default=0)),
                ('donationsDelta', models.IntegerField(default=0)),
                ('deckLink', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSeasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30)),
                ('rank', models.IntegerField(default=0)),
                ('trophies', models.IntegerField(default=0)),
                ('bestTrophies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crownsEarned', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Battles')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Decks')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSeason',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clanwar.Players')),
                ('rank', models.IntegerField(default=0)),
                ('trophies', models.IntegerField(default=0)),
                ('bestTrophies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clanwar.Players')),
                ('total', models.IntegerField(default=0)),
                ('tournamentGames', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('warDayWins', models.IntegerField(default=0)),
                ('winsPercent', models.FloatField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('lossesPercent', models.FloatField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('drawsPercent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clanwar.Players')),
                ('clanCardsCollected', models.IntegerField(default=0)),
                ('tournamentCardsWon', models.IntegerField(default=0)),
                ('maxTrophies', models.IntegerField(default=0)),
                ('threeCrownWins', models.IntegerField(default=0)),
                ('cardsFound', models.IntegerField(default=0)),
                ('totalDonations', models.IntegerField(default=0)),
                ('challengeMaxWins', models.IntegerField(default=0)),
                ('challengeCardsWon', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Players'),
        ),
        migrations.AddField(
            model_name='previousseasons',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Players'),
        ),
        migrations.AddField(
            model_name='players',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Arenas'),
        ),
        migrations.AddField(
            model_name='players',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Clans'),
        ),
        migrations.AddField(
            model_name='players',
            name='currentDeck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Decks'),
        ),
        migrations.AddField(
            model_name='oponents',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Players'),
        ),
        migrations.AddField(
            model_name='clans',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clanwar.Locations'),
        ),
        migrations.AddField(
            model_name='cards',
            name='decks',
            field=models.ManyToManyField(to='clanwar.Decks'),
        ),
        migrations.AddField(
            model_name='battles',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Players'),
        ),
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together=set([('battle', 'player')]),
        ),
        migrations.AddField(
            model_name='stats',
            name='favoriteCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanwar.Cards'),
        ),
        migrations.AlterUniqueTogether(
            name='previousseasons',
            unique_together=set([('id', 'player')]),
        ),
        migrations.AlterUniqueTogether(
            name='oponents',
            unique_together=set([('battle', 'player')]),
        ),
        migrations.AlterUniqueTogether(
            name='battles',
            unique_together=set([('player', 'utcTime')]),
        ),
    ]
