# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0003_auto_20180721_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battles',
            name='challengeType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
