# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-27 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0003_auto_20180627_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenas',
            name='league_id',
            field=models.CharField(max_length=30),
        ),
    ]
