# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0004_auto_20180721_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opponents',
            name='startTrophies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='startTrophies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
