# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0004_auto_20180627_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenas',
            name='season_reward_chest',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
