# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-27 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0005_auto_20180627_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenas',
            name='force_quest_chest_cycle',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
