# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0006_auto_20180627_0123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oponents',
            new_name='Opponents',
        ),
        migrations.AlterField(
            model_name='battles',
            name='mode_cardLevels',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='battles',
            name='winCountBefore',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='previousseasons',
            unique_together=set([('season', 'player')]),
        ),
    ]
