# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0008_auto_20180627_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clanwar.Arenas'),
        ),
        migrations.AlterField(
            model_name='players',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clanwar.Clans'),
        ),
    ]
