# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-27 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0009_auto_20180627_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
