# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0010_auto_20180627_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='icon',
            field=models.URLField(null=True),
        ),
    ]
