# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0013_auto_20180627_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenas',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
