# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0015_auto_20180706_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousseasons',
            name='arena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clanwar.Arenas'),
        ),
    ]
