# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0016_previousseasons_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenas',
            name='max_trophy_limit',
            field=models.IntegerField(default=0),
        ),
    ]
